### ISSUE TITLE
Possible null pointer when deleting a build and artifactory artifact manager is not configured

### ISSUE THREAD

**Issue by jonesbusy** [jenkinsci/artifactory-artifact-manager-plugin#26]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

All

### Reproduction steps

Delete a build without configuring the plugin

### Expected Results

No error

### Actual Results

[2024-04-04T11:31:00.090+0000] [WARNING] jenkins.util.Listeners lambda$notify$0 # null
java.lang.NullPointerException: Cannot invoke "io.jenkins.plugins.artifactory_artifacts.ArtifactoryArtifactManagerFactory.getConfig()" because "artifactoryArtifactManagerFactory" is null
at io.jenkins.plugins.artifactory_artifacts.Utils.getArtifactConfig(Utils.java:26)
at io.jenkins.plugins.artifactory_artifacts.ArtifactoryArtifactManager$ArtifactoryItemListener.onDeleted(ArtifactoryArtifactManager.java:341)
at hudson.model.listeners.ItemListener.lambda$fireOnDeleted$3(ItemListener.java:210)

**Comment by jonesbusy** [comment]
Fixed on https://github.com/jenkinsci/artifactory-artifact-manager-plugin/releases/tag/73.v0e73747d2f6f
